name: Deploy Infra con CloudFormation

on:
  workflow_dispatch: {}  # habilita ejecuci√≥n manual

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::200093566387:role/github-deployer-role

      - name: Deploy root stack (dev)
        run: |
          aws cloudformation deploy \
            --stack-name nequi-root-dev \
            --template-file infraestructura/stacks/main.yml \
            --parameter-overrides \
              TemplatesBaseUrl="https://s3.amazonaws.com/lambda-code-200093566387-us-east-1-dev/infra_templates" \
              Environment=dev \
              Region=us-east-1 \
              EventTableName=EventTable \
              ApiKeyName=events-api-key \
              ApiKeyValue="" \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
